version: "3.5"
services:
  api:
    image: api:0.0.4
    ports:
      - "8000:8000"
    secrets:
      - MYSQL_ROOT_PASSWORD
  mysql:
    image: mysql
    command:
    - /bin/bash
    - -c
    - "MYSQL_ROOT_PASSWORD=$$(cat /run/secrets/MYSQL_ROOT_PASSWORD) && mysqld"
    ports: 
      - "3306:3306"
    volumes:
      - /data:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
